[project]
name = "image-optimize"
version = "0.1.0"
description = "Python tool for automatic CV image optimization and PDF integration"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pillow>=11.3.0",
    "pymupdf>=1.26.3",
]
